config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :users
  resources :ingredients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :allergies
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :allergies
end

app/controllers/allergy_controller.rb
class AllergiesController < ApplicationController

  def index
    @allergies = Allergy.all
  end

  def show
    @allergy = Allergy.find(params[:id])
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def user_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @users = User.all
  end

  def create
    @recipe = Recipe.create(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #induces

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @allergies = Allergy.all
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>All Ingredients</h1>

<h3><a href="../ingredients/new">Create Ingredient</a></h3>

<% @ingredients.each do |item| %>
  <%= link_to item.name, ingredient_path(item) %>  Number of Allergies = <%= item.allergies.count  %><br>
<%end %>

app/views/ingredients/show.html.erb
<h1>User: <%=@ingredient.name %></h1>

<h4>Recipies associated with <%=@ingredient.name %> </h4>

<% @ingredient.recipes.each do |i| %><br>
  <%= link_to i.name, recipe_path(i) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<h3><a href="../recipes/new">Create Recipe</a></h3>

<% @recipes.each do |recipe| %>
  <%= link_to recipe.name, recipe_path(recipe) %> - Number of Ingredients: <%= recipe.ingredients.count %><br>
<%end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%=form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :user %>
  <%= f.collection_select :user_id, @users, :id, :name %>

  <%= f.submit %>

<% end %>

app/views/recipes/show.html.erb
<h1>User: <%=@recipe.name %></h1>

<h4>Ingredients:</h4>

<% @recipe.ingredients.each do |i| %><br>
  <%= link_to i.name, ingredient_path(i) %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(user) %><br>

<%end %>

app/views/users/show.html.erb
<h1>User: <%=@user.name %></h1>

<h4>Recipes:</h4>

<% @user.recipes.each do |recipe| %>
<%= link_to recipe.name, recipe_path(recipe) %><br>
<% end %>

<br>
<h4>Allergies:</h4>

<% @user.allergies.each do |item| %>
  <%= item.ingredient.name %><br>
<% end %>